#!/bin/bash

# Downloads and installs wp-cli - http://wp-cli.org/


if [ -x "$(command -v wp)" ]; then
	echo >&2 "wp-cli is already installed!"
	exit 1
fi

curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/bin/wp
